# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './displot.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.imageTab = QtWidgets.QWidget()
        self.imageTab.setEnabled(True)
        self.imageTab.setObjectName("imageTab")
        self.gridLayout = QtWidgets.QGridLayout(self.imageTab)
        self.gridLayout.setContentsMargins(0, 0, 0, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.imageTab)
        self.graphicsView.setEnabled(False)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.imageTab, "")
        self.openTab = QtWidgets.QWidget()
        self.openTab.setObjectName("openTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.openTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.openTab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.openTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.infoBar = QtWidgets.QHBoxLayout()
        self.infoBar.setObjectName("infoBar")
        self.imageInfo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageInfo.sizePolicy().hasHeightForWidth())
        self.imageInfo.setSizePolicy(sizePolicy)
        self.imageInfo.setMinimumSize(QtCore.QSize(300, 0))
        self.imageInfo.setFrameShape(QtWidgets.QFrame.Box)
        self.imageInfo.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageInfo.setObjectName("imageInfo")
        self.infoBar.addWidget(self.imageInfo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infoBar.addItem(spacerItem)
        self.zoomLabel = QtWidgets.QLabel(self.centralwidget)
        self.zoomLabel.setObjectName("zoomLabel")
        self.infoBar.addWidget(self.zoomLabel)
        self.zoomCtrl = QtWidgets.QSpinBox(self.centralwidget)
        self.zoomCtrl.setToolTip("")
        self.zoomCtrl.setStatusTip("")
        self.zoomCtrl.setPrefix("")
        self.zoomCtrl.setMinimum(5)
        self.zoomCtrl.setMaximum(400)
        self.zoomCtrl.setProperty("value", 100)
        self.zoomCtrl.setObjectName("zoomCtrl")
        self.infoBar.addWidget(self.zoomCtrl)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(150, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.infoBar.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.infoBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuScan = QtWidgets.QMenu(self.menubar)
        self.menuScan.setObjectName("menuScan")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen_Image = QtWidgets.QAction(MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionOpen_Sequence = QtWidgets.QAction(MainWindow)
        self.actionOpen_Sequence.setObjectName("actionOpen_Sequence")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Image_As = QtWidgets.QAction(MainWindow)
        self.actionSave_Image_As.setEnabled(False)
        self.actionSave_Image_As.setObjectName("actionSave_Image_As")
        self.actionQuick_scan = QtWidgets.QAction(MainWindow)
        self.actionQuick_scan.setObjectName("actionQuick_scan")
        self.actionRemove_background = QtWidgets.QAction(MainWindow)
        self.actionRemove_background.setObjectName("actionRemove_background")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionOpen_Sequence)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Image_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuScan.addAction(self.actionQuick_scan)
        self.menuImage.addAction(self.actionRemove_background)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "displot"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.imageTab), _translate("MainWindow", "No Image"))
        self.label.setText(_translate("MainWindow", "No image loaded."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.openTab), _translate("MainWindow", "+"))
        self.imageInfo.setText(_translate("MainWindow", "No image loaded"))
        self.zoomLabel.setText(_translate("MainWindow", "Zoom:"))
        self.zoomCtrl.setSuffix(_translate("MainWindow", "%"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuScan.setTitle(_translate("MainWindow", "Scan"))
        self.menuImage.setTitle(_translate("MainWindow", "Image"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionOpen_Sequence.setText(_translate("MainWindow", "Open Sequence"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_Image_As.setText(_translate("MainWindow", "Save Image As..."))
        self.actionQuick_scan.setText(_translate("MainWindow", "Quick scan"))
        self.actionRemove_background.setText(_translate("MainWindow", "Remove background"))

